kind: project
metadata:
  name: hugging-face-trainer-nashtech
spec:
  functions: []
  workflows: []
  artifacts: []
  conda: ''
  source: ''
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
